/** Allowed Lucide icon keys for store categories. */
const CATEGORY_ICON_KEYS = [
  'layers',
  'book-open',
  'book',
  'library',
  'graduation-cap',
  'backpack',
  'briefcase',
  'shopping-bag',
  'shirt',
  'footprints',
  'dumbbell',
  'trophy',
  'pencil',
  'pen-line',
  'notebook-pen',
  'ruler',
  'palette',
  'laptop',
  'headphones',
  'glasses',
  'watch',
  'gift',
  'heart',
  'star',
  'tag',
  'package',
  'school',
  'landmark',
  'atom',
  'flask-conical',
  'calculator',
  'globe',
];

module.exports = { CATEGORY_ICON_KEYS };
