module.exports = {
  Store: require('./Store'),
  SubscriptionPlan: require('./SubscriptionPlan'),
  SubscriptionPayment: require('./SubscriptionPayment'),
  User: require('./User'),
  PasswordResetToken: require('./PasswordResetToken'),
  RegistrationOtp: require('./RegistrationOtp'),
  Category: require('./Category'),
  CategoryTemplate: require('./CategoryTemplate'),
  Product: require('./Product'),
  Review: require('./Review'),
  Cart: require('./Cart'),
  Discount: require('./Discount'),
  Order: require('./Order'),
  Payment: require('./Payment'),
  Receipt: require('./Receipt'),
  StoreCustomer: require('./StoreCustomer'),
  Subscriber: require('./Subscriber'),
  Counter: require('./Counter'),
  PlatformSetting: require('./PlatformSetting'),
  Wishlist: require('./Wishlist'),
  Address: require('./Address'),
};
